/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImpactMapRouteImport } from './routes/impact-map'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as MissionsRouteImport } from './routes/missions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactMapRoute = ImpactMapRouteImport.update({
  id: '/impact-map',
  path: '/impact-map',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/impact-map': typeof ImpactMapRoute
  '/leaderboard': typeof LeaderboardRoute
  '/missions': typeof MissionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/impact-map': typeof ImpactMapRoute
  '/leaderboard': typeof LeaderboardRoute
  '/missions': typeof MissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/impact-map': typeof ImpactMapRoute
  '/leaderboard': typeof LeaderboardRoute
  '/missions': typeof MissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/impact-map' | '/leaderboard' | '/missions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/impact-map' | '/leaderboard' | '/missions'
  id: '__root__' | '/' | '/impact-map' | '/leaderboard' | '/missions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImpactMapRoute: typeof ImpactMapRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MissionsRoute: typeof MissionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact-map': {
      id: '/impact-map'
      path: '/impact-map'
      fullPath: '/impact-map'
      preLoaderRoute: typeof ImpactMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImpactMapRoute: ImpactMapRoute,
  LeaderboardRoute: LeaderboardRoute,
  MissionsRoute: MissionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
